[package]
name = "rover"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "*"
ansi_term = "0.12"
text_io = "0.1.9"

num-traits = "0.2"
num-derive = "0.3"

[features]
trace_exec = []
print_code = []
ast_interpreter = []